# Interview Question Series 2 

## Python Programming - Numpy

### 1. Why is python numpy better than lists? 

<details>
<summary>Click here for the solution</summary>
  
Python numpy arrays should be considered instead of a list because they are fast, consume less memory and convenient with lots of functionality. 
</details>

### 2. Describe the map function in Python

<details>
<summary>Click here for the solution</summary>

map function executes the function given as the first argument on all the elements of the iterable given as the second argument. 
</details>

### 3. Generate array of ‘100’ random numbers sampled from a standard normal distribution using Numpy

<details>
<summary>Click here for the solution</summary>

```python
np.random.rand(100)
```
will create 100 random numbers generated from standard normal distribution with mean 0 and standard deviation 1. 
</details>

### 4. How to count the occurrence of each value in a numpy array? 

<details>
<summary>Click here for the solution</summary>

Use numpy.bincount()
```python  
>>> arr = numpy.array([0, 5, 5, 0, 2, 4, 3, 0, 0, 5, 4, 1, 9, 9]) 
>>> numpy.bincount(arr) 
# output:
array([4, 1, 1, 1, 2, 3, 0, 0, 0, 2], dtype=int64)
```
The argument to bincount( must consist of booleans or positive integers. Negative integers are invalid. 
</details>

### 5. Does Numpy Support Nan? 

<details>
<summary>Click here for the solution</summary>

nan, short for “not a number”, is a special floating point value defined by the IEEE-754 specification. Python numpy supports nan but the definition of nan is more system dependent and some systems don't have an all round support for it like older cray and vax computers. 
</details>

### 6. What does ravel() function in numpy do? 

<details>
<summary>Click here for the solution</summary>

It combines multiple numpy arrays into a single array 
</details>

### 7. What is the meaning of axis=0 and axis=1? 

<details>
<summary>Click here for the solution</summary>

`axis=0` is meant for reading rows
  
`axis=1` is meant for reading columns 
</details>

### 8. What is numpy and describe its use cases? 

<details>
<summary>Click here for the solution</summary>

Numpy is a package library for Python, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high level mathematical functions. In simple words, Numpy is an optimized version of Python lists like Financial functions, Linear Algebra, Statistics, Polynomials, Sorting and Searching etc. 
</details>

### 9. How to remove from one array those items that exist in another? 

<details>
<summary>Click here for the solution</summary>
    
```python
>>> a = np.array([5, 4, 3, 2, 1]) 
>>> b = np.array([4, 8, 9, 10, 1]) 
# From 'a' remove all of 'b' 
>>> np.setdiff1d(a,b) 
# Output: 
array([5, 3, 2]) 
```
</details>

### 10. How to sort a numpy array by a specific column in a 2D array? 

<details>
<summary>Click here for the solution</summary>
    
```python
#Choose column 2 as an example 
>>> import numpy as np 
>>> arr = np.array([[1, 2, 3], [4, 5, 6], [0,0,1]]) 
>>> arr[arr[:,1].argsort()] 
# Output 
array([[0, 0, 1], [1, 2, 3], [4, 5, 6]]) 
```
</details>

### 11. How to reverse a numpy array in the most efficient way? 

<details>
<summary>Click here for the solution</summary>
    
```python
>>> import numpy as np 
>>> arr = np.array([9, 10, 1, 2, 0]) 
>>> reverse_arr = arr[::-1]
>>> reverse_arr
# output
array([ 0,  2,  1, 10,  9])
```
    
</details>

### 12. How to calculate percentiles when using numpy? 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> arr = np.array([11, 22, 33, 44 ,55 ,66, 77]) 
>>> perc = np.percentile(arr, 40) #Returns the 40th percentile 
>>> print(perc)
# output
37.400000000000006
```
</details>

### 13. What Is The Difference Between Numpy And Scipy? 

<details>
<summary>Click here for the solution</summary>

__NumPy__ would contain nothing but the array data type and the most basic operations: 

indexing, sorting, reshaping, basic element wise functions, et cetera. All numerical code would reside in SciPy. 
    
__SciPy__ contains more fully-featured versions of the linear algebra modules, as well as many other numerical algorithms. 
</details>

### 14. What Is The Preferred Way To Check For An Empty (zero Element) Array?

<details>
<summary>Click here for the solution</summary>

For a numpy array, use the size attribute. The size attribute is helpful for determining the length of numpy array: 
```python
>>> arr = numpy.zeros((1,0)) 
>>> arr.size 
# output
0
```
</details>

### 15. What Is The Difference Between Matrices And Arrays? 

<details>
<summary>Click here for the solution</summary>

Matrices can only be two-dimensional, whereas arrays can have any number of dimensions.
</details>

### 16. How can you find the indices of an array where a condition is true? 

<details>
<summary>Click here for the solution</summary>
    
Given an array a, the condition arr > 3 returns a boolean array and since False is interpreted as 0 in Python and NumPy. 

```python
>>> import numpy as np 
>>> arr = np.array([[9,8,7],[6,5,4],[3,2,1]]) 
>>> arr > 3 
array([[True, True, True], 
    [ True, True, True], 
    [False, False, False]], dtype=bool) 
```

### 17. How to find the maximum and minimum value of a given flattened array? 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> a = np.arange(4).reshape((2,2)) 
>>> max_val = np.amax(a) 
>>> min_val = np.amin(a) 
>>> print(f"min_val: {min_val}")
>>> print(f"max_val: {max_val}")
min_val: 0
max_val: 3
```
</details>

### 18. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis. 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> arr = np.arange(28).reshape((4, 7)) 
>>> res = np.ptp(arr, 1)
>>> res
array([6, 6, 6, 6])
```
</details>

### 19. Find median of a numpy flattened array 

<details>
<summary>Click here for the solution</summary>

```python
>>> arr = np.arange(20).reshape((4, 5)) 
>>> res = np.median(arr) 
>>> res
9.5
```
</details>

### 20. Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> x = np.arange(16) 
>>> mean = np.mean(x) 
>>> std = np.std(x) 
>>> var = np.var(x)
```
</details>

### 21. Calculate covariance matrix between two numpy arrays 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> x = np.array([2, 1, 0]) 
>>> y = np.array([2, 3, 3]) 
>>> cov_arr = np.cov(x, y) 
>>> cov_arr
array([[ 1.        , -0.5       ],
       [-0.5       ,  0.33333333]])
```
</details>

### 22. Compute Compute pearson product-moment correlation coefficients of two given numpy arrays 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> x = np.array([0, 1, 3]) 
>>> y = np.array([2, 4, 5]) 
>>> cross_corr = np.corrcoef(x, y) 
cross_corr
array([[1.        , 0.92857143],
       [0.92857143, 1.        ]])
```
</details>

### 23. Develop a numpy program to compute the histogram of nums against the bins 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1]) 
>>> bins = np.array([0, 1, 2, 3]) 
>>> np.histogram(nums, bins) 
(array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))
```
</details>

### 24. Get the powers of an array values element-wise 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> x = np.arange(7) 
>>> np.power(x, 3)
array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)
```
</details>

### 25. Write a NumPy program to get true division of the element-wise array inputs 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> x = np.arange(10) 
>>> np.true_divide(x, 3) 
array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])
```
</details>

## Pandas  

### 26. What is a series in pandas? 

<details>
<summary>Click here for the solution</summary>
    
A Series is defined as a one-dimensional array that is capable of storing various data types. The row labels of the series are called the index. By using a 'series' method, we can easily convert the list, tuple, and dictionary into series. A Series cannot contain multiple columns. 

### 27. What features make Pandas such a reliable option to store tabular data? 

Memory Efficient, Data Alignment, Reshaping, Merge and join and Time Series. 

### 28. What is reindexing in pandas? 

<details>
<summary>Click here for the solution</summary>
    
Reindexing is used to conform DataFrame to a new index with optional filling logic. It places NA/NaN in that location where the values are not present in the previous index. It returns a new object unless the new index is produced as equivalent to the current one, and the value of copy becomes False. It is used to change the index of the rows and 
columns of the DataFrame. 
</details>

### 29. How will you create a series from dict in Pandas? 

<details>
<summary>Click here for the solution</summary>

A Series is defined as a one-dimensional array that is capable of storing various data types. 
```python
>>> import pandas as pd   
>>> info = {'x' : 0., 'y' : 1., 'z' : 2.}   
>>> a = pd.Series(info) 
x    0.0
y    1.0
z    2.0
dtype: float64
```
</details>
 

### 30. How can we create a copy of the series in Pandas? 

<details>
<summary>Click here for the solution</summary>
    
Use pandas.Series.copy method 
```python
>>> import pandas as pd 
>>> pd.Series.copy(deep=True)
```
</details>

### 31. What is groupby in Pandas? 

<details>
<summary>Click here for the solution</summary>
    
GroupBy is used to split the data into groups. It groups the data based on some criteria. Grouping also provides a mapping of labels to the group names. It has a lot of variations that can be defined with the parameters and makes the task of splitting the data quick and easy. 
</details>

### 32. What is vectorization in Pandas? 

<details>
<summary>Click here for the solution</summary>
    
Vectorization is the process of running operations on the entire array. This is done to reduce the amount of iteration performed by the functions. Pandas have a number of vectorized functions like aggregations, and string functions that are optimized to operate specifically on series and DataFrames. So it is preferred to use the vectorized pandas functions to execute the operations quickly. 
</details>

### 33. Mention the different types of Data Structures in Pandas 

<details>
<summary>Click here for the solution</summary>
    
Pandas provide two data structures, which are supported by the pandas library, Series, and DataFrames. Both of these data structures are built on top of the NumPy. 
</details>

### 34. What Is Time Series In pandas 

<details>
<summary>Click here for the solution</summary>
    
A time series is an ordered sequence of data which basically represents how some quantity changes over time. pandas contains extensive capabilities and features for working with time series data for all domains. 
</details>

### 35. How to convert pandas dataframe to numpy array? 

<details>
<summary>Click here for the solution</summary>
    
The function to_numpy() is used to convert the DataFrame to a NumPy array. 
DataFrame.to_numpy(self, dtype=None, copy=False) The dtype parameter defines the data type to pass to the array and the copy ensures the 
returned value is not a view on another array. 
</details>

### 36. Write a Pandas program to get the first 5 rows of a given DataFrame 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 
'Matthew', 'Laura', 'Kevin', 'Jonas'],} 
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 
>>> df = pd.DataFrame(exam_data , index=labels) 
>>> df.iloc[:5] 
```
|  | name |
| --- | ----------- |
| a | Anastasia |
| b | Dima |
| c | Katherine |
| d | James |
| e | Emily |
</details>

### 37. Develop a Pandas program to create and display a one-dimensional array-like object containing an array of data. 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> pd.Series([2, 4, 6, 8, 10])
```
</details>

### 38. Write a Python program to convert a Panda module Series to Python list and it's type. 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> ds = pd.Series([2, 4, 6, 8, 10]) 
>>> type(ds) 
>>> ds.tolist() 
>>> type(ds.tolist()) 
list
```
</details>

### 39. Develop a Pandas program to add, subtract, multiple and divide two Pandas Series. 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> ds1 = pd.Series([2, 4, 6, 8, 10]) 
>>> ds2 = pd.Series([1, 3, 5, 7, 9]) 
>>> sum = ds1 + ds2 
>>> sub = ds1 - ds2 
>>> mul = ds1 * ds2 
>>> div = ds1 / ds2 
```
</details>

### 40. Develop a Pandas program to compare the elements of the two Pandas Series. 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> ds1 = pd.Series([2, 4, 6, 8, 10]) 
>>> ds2 = pd.Series([1, 3, 5, 7, 10]) 
>>> ds1 == ds2 
0    False
1    False
2    False
3    False
4     True
dtype: bool

>>> ds1 > ds2 
0     True
1     True
2     True
3     True
4    False
dtype: bool
    
>>> ds1 < ds2 
0    False
1    False
2    False
3    False
4    False
dtype: bool
```
</details>

### 41. Develop a Pandas program to change the data type of given a column or a Series. 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> s1 = pd.Series(['100', '200', 'python', '300.12', '400']) 
>>> s2 = pd.to_numeric(s1, errors='coerce') 
>>> s2 
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64
```
</details>
 

### 42. Write a Pandas program to convert Series of lists to one Series 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> s = pd.Series([ ['Red', 'Black'], ['Red', 'Green', 'White'] , ['Yellow']]) 
>>> s = s.apply(pd.Series).stack().reset_index(drop=True) 
>>> s
0       Red
1     Black
2       Red
3     Green
4     White
5    Yellow
dtype: object
```
</details>

### 43. Write a Pandas program to create a subset of a given series based on value and condition 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10]) 
>>> n = 6 
>>> new_s = s[s < n] 
>>> new_s 
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
```
</details>

### 44. Develop a Pandas code to alter the order of index in a given series 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E']) 
>>> s.reindex(index = ['B','A','C','D','E']) 
B    2
A    1
C    3
D    4
E    5
dtype: int64
```
</details>

### 45. Write a Pandas code to get the items of a given series not present in another given series. 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> sr1 = pd.Series([1, 2, 3, 4, 5]) 
>>> sr2 = pd.Series([2, 4, 6, 8, 10]) 
>>> result = sr1[~sr1.isin(sr2)] 
>>> result 
0    1
2    3
4    5
dtype: int64
```
</details>

### 46. What is the difference between the two data series df[‘Name’] and   df.loc[:, ‘Name’]? 

<details>
<summary>Click here for the solution</summary>
    
__df[‘Name’]__: a view of the original dataframe

__df.loc[:, ‘Name’]__: a copy of the original dataframe. 

</details>

### 47. Write a Pandas program to display the most frequent value in a given series and replace everything else as “replaced” in the series. 

<details>
<summary>Click here for the solution</summary>

```python
>>> import pandas as pd 
>>> import numpy as np 
>>> np.random.RandomState(100) 
>>> num_series = pd.Series(np.random.randint(1, 5, [15])) 
>>> result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'replaced' 
print('**This solution needs to be fixed**')
```
</details>