# Interview Question Series 2 

## Python Programming - Numpy

### 1. Why is python numpy better than lists? 

<details>
<summary>Click here for the solution</summary>
  
Python numpy arrays should be considered instead of a list because they are fast, consume less memory and convenient with lots of functionality. 
</details>

### 2. Describe the map function in Python

<details>
<summary>Click here for the solution</summary>

map function executes the function given as the first argument on all the elements of the iterable given as the second argument. 
</details>

### 3. Generate array of ‘100’ random numbers sampled from a standard normal distribution using Numpy

<details>
<summary>Click here for the solution</summary>

```python
np.random.rand(100)
```
will create 100 random numbers generated from standard normal distribution with mean 0 and standard deviation 1. 
</details>

### 4. How to count the occurrence of each value in a numpy array? 

<details>
<summary>Click here for the solution</summary>

Use numpy.bincount()
```python  
>>> arr = numpy.array([0, 5, 5, 0, 2, 4, 3, 0, 0, 5, 4, 1, 9, 9]) 
>>> numpy.bincount(arr) 
# output:
array([4, 1, 1, 1, 2, 3, 0, 0, 0, 2], dtype=int64)
```
The argument to bincount( must consist of booleans or positive integers. Negative integers are invalid. 
</details>

### 5. Does Numpy Support Nan? 

<details>
<summary>Click here for the solution</summary>

nan, short for “not a number”, is a special floating point value defined by the IEEE-754 specification. Python numpy supports nan but the definition of nan is more system dependent and some systems don't have an all round support for it like older cray and vax computers. 
</details>

### 6. What does ravel() function in numpy do? 

<details>
<summary>Click here for the solution</summary>

It combines multiple numpy arrays into a single array 
</details>

### 7. What is the meaning of axis=0 and axis=1? 

<details>
<summary>Click here for the solution</summary>

`axis=0` is meant for reading rows
  
`axis=1` is meant for reading columns 
</details>

### 8. What is numpy and describe its use cases? 

<details>
<summary>Click here for the solution</summary>

Numpy is a package library for Python, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high level mathematical functions. In simple words, Numpy is an optimized version of Python lists like Financial functions, Linear Algebra, Statistics, Polynomials, Sorting and Searching etc. 
</details>

### 9. How to remove from one array those items that exist in another? 

<details>
<summary>Click here for the solution</summary>
    
```python
>>> a = np.array([5, 4, 3, 2, 1]) 
>>> b = np.array([4, 8, 9, 10, 1]) 
# From 'a' remove all of 'b' 
>>> np.setdiff1d(a,b) 
# Output: 
array([5, 3, 2]) 
```
</details>

### 10. How to sort a numpy array by a specific column in a 2D array? 

<details>
<summary>Click here for the solution</summary>
    
```python
#Choose column 2 as an example 
>>> import numpy as np 
>>> arr = np.array([[1, 2, 3], [4, 5, 6], [0,0,1]]) 
>>> arr[arr[:,1].argsort()] 
# Output 
array([[0, 0, 1], [1, 2, 3], [4, 5, 6]]) 
```
</details>

### 11. How to reverse a numpy array in the most efficient way? 

<details>
<summary>Click here for the solution</summary>
    
```python
>>> import numpy as np 
>>> arr = np.array([9, 10, 1, 2, 0]) 
>>> reverse_arr = arr[::-1]
>>> reverse_arr
# output
array([ 0,  2,  1, 10,  9])
```
    
</details>

### 12. How to calculate percentiles when using numpy? 

<details>
<summary>Click here for the solution</summary>

```python
>>> import numpy as np 
>>> arr = np.array([11, 22, 33, 44 ,55 ,66, 77]) 
>>> perc = np.percentile(arr, 40) #Returns the 40th percentile 
>>> print(perc)
# output
37.400000000000006
```
</details>

### 13. What Is The Difference Between Numpy And Scipy? 

<details>
<summary>Click here for the solution</summary>

__NumPy__ would contain nothing but the array data type and the most basic operations: 

indexing, sorting, reshaping, basic element wise functions, et cetera. All numerical code would reside in SciPy. 
    
__SciPy__ contains more fully-featured versions of the linear algebra modules, as well as many other numerical algorithms. 
</details>

### 14. What Is The Preferred Way To Check For An Empty (zero Element) Array?

<details>
<summary>Click here for the solution</summary>

For a numpy array, use the size attribute. The size attribute is helpful for determining the length of numpy array: 
```python
>>> arr = numpy.zeros((1,0)) 
>>> arr.size 
# output
0
```
</details>

### 15. What Is The Difference Between Matrices And Arrays? 

<details>
<summary>Click here for the solution</summary>

Matrices can only be two-dimensional, whereas arrays can have any number of dimensions.
</details>